.mlasdo_write_importance_report <- function(report_dir,
                                            sorted_importance,
                                            knee_index,
                                            selected_features,
                                            rf_performance = NULL,
                                            svm_results = NULL,
                                            anomalies = NULL,
                                            domain_expert = NULL,
                                            individual_interpretability = NULL) {
  dir.create(report_dir, recursive = TRUE, showWarnings = FALSE)
  assets_dir <- file.path(report_dir, "report_assets")
  if (dir.exists(assets_dir)) {
    unlink(assets_dir, recursive = TRUE, force = TRUE)
  }
  dir.create(assets_dir, recursive = TRUE, showWarnings = FALSE)

  importance_df <- data.frame(
    Feature = names(sorted_importance),
    Importance = as.numeric(sorted_importance),
    stringsAsFactors = FALSE
  )

  importance_path <- file.path(assets_dir, "feature_importance_values.rds")
  summary_path <- file.path(assets_dir, "feature_importance_summary.rds")
  report_path <- file.path(report_dir, "mlasdo_report.Rmd")

  saveRDS(importance_df, importance_path)
  saveRDS(
    list(
      knee_index = knee_index,
      selected_features = selected_features
    ),
    summary_path
  )

  rf_report_path <- NULL
  if (!is.null(rf_performance)) {
    rf_report_path <- file.path(assets_dir, "rf_performance_data.rds")
    saveRDS(rf_performance, rf_report_path)
  }

  svm_report_path <- NULL
  svm_payload <- .mlasdo_build_svm_report_payload(svm_results)
  if (!is.null(svm_payload)) {
    svm_report_path <- file.path(assets_dir, "svm_report_data.rds")
    saveRDS(svm_payload, svm_report_path)
  }

  anomaly_report_path <- NULL
  if (!is.null(anomalies)) {
    anomaly_report_path <- file.path(assets_dir, "anomaly_report_data.rds")
    saveRDS(anomalies, anomaly_report_path)
  }

  domain_expert_path <- NULL
  if (!is.null(domain_expert) && !is.null(domain_expert$table)) {
    domain_expert_path <- file.path(assets_dir, "domain_expert_table.rds")
    saveRDS(domain_expert$table, domain_expert_path)
  }

  individual_interpretability_path <- NULL
  if (!is.null(individual_interpretability) &&
      !is.null(individual_interpretability$data) &&
      nrow(individual_interpretability$data) > 0) {
    individual_interpretability_path <- file.path(assets_dir, "individual_interpretability_data.rds")
    saveRDS(individual_interpretability$data, individual_interpretability_path)
  }

  report_contents <- c(
    "---",
    "title: \"MLASDO Summary\"",
    "output:",
    "  html_document:",
    "    df_print: paged",
    "---",
    "",
    "# Feature Importance {.tabset}",
    "",
    "## Importance Curve",
    "",
    "```{r importance-curve, echo=FALSE}",
    "library(ggplot2)",
    "importance_df <- readRDS('report_assets/feature_importance_values.rds')",
    "meta <- readRDS('report_assets/feature_importance_summary.rds')",
    "importance_df$Rank <- seq_len(nrow(importance_df))",
    "knee_idx <- meta$knee_index",
    "",
    "ggplot(importance_df, aes(x = Rank, y = Importance)) +",
    "  geom_line() +",
    "  geom_point(size = 0.8) +",
    "  geom_vline(xintercept = knee_idx, linetype = 'dashed', color = 'red') +",
    "  annotate(",
    "    'text',",
    "    x = knee_idx + 1,",
    "    y = max(importance_df$Importance, na.rm = TRUE) * 0.8,",
    "    label = sprintf('Elbow: %d', knee_idx),",
    "    color = 'red',",
    "    angle = 90,",
    "    vjust = 0.5",
    "  ) +",
    "  labs(",
    "    title = 'Variable Importance Curve',",
    "    x = 'Rank',",
    "    y = 'Importance'",
    "  ) +",
    "  theme_minimal()",
    "```",
    "",
    "```{r importance-table, echo=FALSE}",
    "library(DT)",
    "importance_df <- readRDS('report_assets/feature_importance_values.rds')",
    "datatable(",
    "  importance_df,",
    "  options = list(pageLength = 20, scrollX = TRUE),",
    "  caption = 'Feature importance ranking'",
    ")",
    "```",
    "",
    "```{r report-data, include=FALSE}",
    "assets_dir <- 'report_assets'",
    "rf_report_path <- file.path(assets_dir, 'rf_performance_data.rds')",
    "svm_report_path <- file.path(assets_dir, 'svm_report_data.rds')",
    "anomaly_report_path <- file.path(assets_dir, 'anomaly_report_data.rds')",
    "domain_expert_path <- file.path(assets_dir, 'domain_expert_table.rds')",
    "individual_data_path <- file.path(assets_dir, 'individual_interpretability_data.rds')",
    "rf_data <- if (file.exists(rf_report_path)) readRDS(rf_report_path) else NULL",
    "svm_data <- if (file.exists(svm_report_path)) readRDS(svm_report_path) else NULL",
    "anomaly_data <- if (file.exists(anomaly_report_path)) readRDS(anomaly_report_path) else NULL",
    "domain_expert_data <- if (file.exists(domain_expert_path)) readRDS(domain_expert_path) else NULL",
    "individual_data <- if (file.exists(individual_data_path)) readRDS(individual_data_path) else NULL",
    "```",
    "",
    "## Random Forest Performance",
    "",
    "```{r rf-performance, echo=FALSE}",
    "if (is.null(rf_data)) {",
    "  cat('Random Forest training was skipped or metrics were not stored for this run.')",
    "} else {",
    "  metric_name <- rf_data$metric",
    "  if (is.null(metric_name) || length(metric_name) == 0) metric_name <- 'Balanced_Accuracy'",
    "  importance_label <- rf_data$importance",
    "  if (is.null(importance_label) || (length(importance_label) == 1 && is.na(importance_label))) importance_label <- 'not specified'",
    "  best_tune <- rf_data$best_tune",
    "  if (!is.null(best_tune)) {",
    "    cat('Best hyperparameter combination (caret):', '\\n')",
    "    print(best_tune)",
    "  } else {",
    "    cat('Best hyperparameter combination could not be determined.', '\\n')",
    "  }",
    "  cat(sprintf('Optimized metric: %s | Feature importance mode: %s', metric_name, importance_label), '\\n\\n')",
    "  library(DT)",
    "  datatable(",
    "    rf_data$results,",
    "    options = list(pageLength = 10, scrollX = TRUE),",
    "    caption = 'Random Forest resampling results'",
    "  )",
    "}",
    "```",
    "",
    "# SVM Results {.tabset}",
    "",
    "## Balanced Accuracy",
    "",
    "```{r svm-ba, echo=FALSE}",
    "if (is.null(svm_data)) {",
    "  cat('SVM training was not executed in this run.')",
    "} else {",
    "  if (!is.null(svm_data$class_roles)) {",
    "    if (!is.null(svm_data$class_roles$positive)) {",
    "      cat(sprintf('Positive class: %s', svm_data$class_roles$positive), '\\n')",
    "    }",
    "    if (!is.null(svm_data$class_roles$negative)) {",
    "      cat(sprintf('Negative class: %s', svm_data$class_roles$negative), '\\n')",
    "    }",
    "    cat('\\n')",
    "  }",
    "  metrics_list <- lapply(svm_data$kernel_details, function(item) {",
    "    df <- readRDS(item$metrics_path)",
    "    df$kernel <- item$kernel",
    "    df",
    "  })",
    "  if (length(metrics_list) > 0) {",
    "    metrics_df <- do.call(rbind, metrics_list)",
    "    library(ggplot2)",
    "    metrics_df$kernel <- factor(metrics_df$kernel, levels = unique(metrics_df$kernel))",
    "    p <- ggplot(metrics_df, aes(x = kernel, y = Balanced_Accuracy, fill = kernel)) +",
    "      geom_boxplot(alpha = 0.7, width = 0.5, outlier.shape = NA) +",
    "      geom_jitter(width = 0.1, alpha = 0.5, size = 1.5) +",
    "      labs(",
    "        title = 'Balanced Accuracy per kernel',",
    "        x = NULL,",
    "        y = 'Balanced Accuracy'",
    "      ) +",
    "      theme_minimal() +",
    "      theme(legend.position = 'none')",
    "    print(p)",
    "    mean_df <- aggregate(Balanced_Accuracy ~ kernel, metrics_df, mean)",
    "    mean_df$Balanced_Accuracy <- round(mean_df$Balanced_Accuracy, 4)",
    "    knitr::kable(mean_df, caption = 'Mean Balanced Accuracy per kernel')",
    "  } else {",
    "    cat('No kernel metrics available.')",
    "  }",
    "}",
    "```",
    "",
    "## Best Hyperparameters",
    "",
    "```{r svm-hyper, echo=FALSE}",
    "if (is.null(svm_data)) {",
    "  cat('SVM training was not executed in this run.')",
    "} else if (length(svm_data$kernel_details) == 0) {",
    "  cat('No kernel details available.')",
    "} else {",
    "  library(DT)",
    "  all_params <- unique(unlist(lapply(",
    "    svm_data$kernel_details,",
    "    function(item) names(item$best_hyperparameters)",
    "  )))",
    "  rows <- lapply(svm_data$kernel_details, function(item) {",
    "    params <- item$best_hyperparameters",
    "    if (is.data.frame(params)) {",
    "      params <- as.list(params[1, , drop = FALSE])",
    "    }",
    "    if (length(params) == 0) {",
    "      params <- list()",
    "    }",
    "    params$kernel <- item$kernel",
    "    as.data.frame(params, stringsAsFactors = FALSE)",
    "  })",
    "  all_cols <- unique(c(\"kernel\", unlist(lapply(rows, names))))",
    "  all_cols <- all_cols[!duplicated(all_cols)]",
    "  rows_aligned <- lapply(rows, function(df) {",
    "    missing <- setdiff(all_cols, names(df))",
    "    for (nm in missing) {",
    "      df[[nm]] <- NA",
    "    }",
    "    df[, all_cols, drop = FALSE]",
    "  })",
    "  hyper_df <- do.call(rbind, rows_aligned)",
    "  datatable(",
    "    hyper_df,",
    "    options = list(pageLength = 5, scrollX = TRUE),",
    "    caption = 'Best hyperparameters learned per kernel'",
    "  )",
    "}",
    "```",
    "",
    "## Distances best SVM",
    "",
    "```{r svm-distances, echo=FALSE}",
    "if (is.null(svm_data)) {",
    "  cat('SVM training was not executed in this run.')",
    "} else {",
    "  best_kernel <- svm_data$best_kernel",
    "  kernel_details <- svm_data$kernel_details",
    "  best_detail <- NULL",
    "  if (!is.null(best_kernel) && length(kernel_details) > 0) {",
    "    for (detail in kernel_details) {",
    "      if (!is.null(detail$kernel) && detail$kernel == best_kernel) {",
    "        best_detail <- detail",
    "        break",
    "      }",
    "    }",
    "  }",
    "  if (is.null(best_detail) && length(kernel_details) > 0) {",
    "    best_detail <- kernel_details[[1]]",
    "  }",
    "  if (is.null(best_detail) || is.null(best_detail$distances_path)) {",
    "    cat('No distance data available for the selected kernel.')",
    "  } else {",
    "    library(DT)",
    "    dist_df <- readRDS(best_detail$distances_path)",
    "    dist_df$kernel <- best_detail$kernel",
    "    caption_txt <- sprintf('Signed distances per subject and fold (%s kernel)', best_detail$kernel)",
    "    datatable(",
    "      dist_df,",
    "      options = list(pageLength = 10, scrollX = TRUE),",
    "      caption = caption_txt",
    "    )",
    "  }",
    "}",
    "```",
    "",
    "# Anomalous Samples {.tabset}",
    "",
    "## Summary",
    "",
    "```{r anomaly-summary, echo=FALSE}",
    "if (is.null(anomaly_data)) {",
    "  cat('Anomaly detection was not executed in this run.')",
    "} else {",
    "  method_label <- anomaly_data$method_label",
    "  cat(sprintf('Method: %s', method_label), '\\n')",
    "  if (!is.null(anomaly_data$positive_class)) {",
    "    cat(sprintf('Positive class: %s', anomaly_data$positive_class), '\\n')",
    "  }",
    "  if (!is.null(anomaly_data$negative_class)) {",
    "    cat(sprintf('Negative class: %s', anomaly_data$negative_class), '\\n')",
    "  }",
    "  if (!is.null(anomaly_data$counts)) {",
    "    knitr::kable(anomaly_data$counts, caption = 'Anomalous individuals per class')",
    "  }",
    "}",
    "```",
    "",
    "## Plot",
    "",
    "```{r anomaly-plot, echo=FALSE}",
    "if (is.null(anomaly_data) || is.null(anomaly_data$plot_path) || !file.exists(anomaly_data$plot_path)) {",
    "  cat('Anomaly plot is not available.')",
    "} else {",
    "  knitr::include_graphics(anomaly_data$plot_path)",
    "}",
    "```",
    "",
    "# Group Interpretability {.tabset}",
    "",
    "In this section we compare clinical distributions for:",
    "",
    "- Clinical Numeric Plot (Anomalous Negative): numeric variables between Anomalous Negative vs. Negative and Anomalous Negative vs. Positive.",
    "- Clinical Numeric Plot (Anomalous Positive): numeric variables between Anomalous Positive vs. Positive and Anomalous Positive vs. Negative.",
    "- Clinical Categorical Plot (Anomalous Negative): categorical variables between Anomalous Negative vs. Negative.",
    "- Clinical Categorical Plot (Anomalous Positive): categorical variables between Anomalous Positive vs. Positive.",
    "",
    "## Clinical Numeric Plot (Anomalous Negative)",
    "",
    "```{r anomaly-num-neg-plot, echo=FALSE}",
    "ct <- if (!is.null(anomaly_data)) anomaly_data$clinical_tests else NULL",
    "if (is.null(ct) || is.null(ct$negative) || is.null(ct$negative$plot_path) ||",
    "    !file.exists(ct$negative$plot_path)) {",
    "  cat('Clinical numeric plot for anomalous negatives is not available.')",
    "} else {",
    "  knitr::include_graphics(ct$negative$plot_path)",
    "}",
    "```",
    "",
    "## Clinical Numeric Plot (Anomalous Positive)",
    "",
    "```{r anomaly-num-pos-plot, echo=FALSE}",
    "ct <- if (!is.null(anomaly_data)) anomaly_data$clinical_tests else NULL",
    "if (is.null(ct) || is.null(ct$positive) || is.null(ct$positive$plot_path) ||",
    "    !file.exists(ct$positive$plot_path)) {",
    "  cat('Clinical numeric plot for anomalous positives is not available.')",
    "} else {",
    "  knitr::include_graphics(ct$positive$plot_path)",
    "}",
    "```",
    "",
    "## Clinical Categorical Plot (Anomalous Negative)",
    "",
    "```{r anomaly-cat-neg-plot, echo=FALSE}",
    "ct <- if (!is.null(anomaly_data)) anomaly_data$clinical_tests else NULL",
    "if (is.null(ct) || is.null(ct$negative) || is.null(ct$negative$categorical_plot_path) ||",
    "    !file.exists(ct$negative$categorical_plot_path)) {",
    "  cat('Categorical plot for anomalous negatives is not available.')",
    "} else {",
    "  knitr::include_graphics(ct$negative$categorical_plot_path)",
    "}",
    "```",
    "",
    "## Clinical Categorical Plot (Anomalous Positive)",
    "",
    "```{r anomaly-cat-pos-plot, echo=FALSE}",
    "ct <- if (!is.null(anomaly_data)) anomaly_data$clinical_tests else NULL",
    "if (is.null(ct) || is.null(ct$positive) || is.null(ct$positive$categorical_plot_path) ||",
    "    !file.exists(ct$positive$categorical_plot_path)) {",
    "  cat('Categorical plot for anomalous positives is not available.')",
    "} else {",
    "  knitr::include_graphics(ct$positive$categorical_plot_path)",
    "}",
    "```",
    "",
    "# Individual Interpretability",
    "",
    "## Domain Expert Knowledge Table",
    "",
    "This table summarises numeric clinical covariates with significant differences (Wilcoxon test) between the Positive and Negative classes, defines thresholds halfway between their medians, and serves as the basis to score each participant individually.",
    "",
    "```{r domain-expert-table, echo=FALSE}",
    "if (is.null(domain_expert_data)) {",
    "  cat('Domain Expert Knowledge Table is not available.')",
    "} else if (nrow(domain_expert_data) == 0) {",
    "  cat('No significant numeric clinical variables were detected between the positive and negative classes.')",
    "} else {",
    "  library(DT)",
    "  datatable(",
    "    domain_expert_data,",
    "    options = list(pageLength = 10, scrollX = TRUE),",
    "    caption = 'Domain Expert Knowledge Table'",
    "  )",
    "}",
    "```",
    "",
    "## Anomalous Individuals",
    "",
    "```{r individual-modal-html, echo=FALSE, results='asis'}",
    "if (!is.null(individual_data) && nrow(individual_data) > 0) {",
    "  cat(\"<div id='individualModal' style='display:none; position:fixed; top:10%; left:20%; width:60%; background:#1e1e1e; color:white; border:1px solid #555; padding:20px; box-shadow:0 0 20px rgba(0,0,0,0.6); z-index:10000; border-radius:6px;'>\")",
    "  cat(\"<span onclick=\\\"document.getElementById('individualModal').style.display='none'\\\" style='float:right;cursor:pointer;font-size:20px;'>&times;</span>\")",
    "  cat(\"<div id='individualModalContent'></div></div>\")",
    "}",
    "```",
    "",
    "```{r individual-interpretability-table, echo=FALSE}",
    "if (is.null(individual_data) || nrow(individual_data) == 0) {",
    "  cat('No anomalous individuals overlapped with the Domain Expert Knowledge Table.')",
    "} else {",
    "  library(DT)",
    "  display_data <- individual_data",
    "  display_data$support_ratio <- round(display_data$support_ratio, 3)",
    "  participant_idx <- which(names(display_data) == 'participant_id')",
    "  participant_target <- if (length(participant_idx) == 1) participant_idx - 1L else 0L",
    "  support_index <- which(names(display_data) == 'support_details')",
    "  oppose_index <- which(names(display_data) == 'oppose_details')",
    "  hide_targets <- c(support_index, oppose_index) - 1L",
    "  hide_targets <- hide_targets[!is.na(hide_targets) & hide_targets >= 0]",
    "  column_defs <- if (length(hide_targets) > 0) list(list(visible = FALSE, targets = hide_targets)) else list()",
    "  row_callback <- NULL",
    "  if (length(support_index) == 1 && length(oppose_index) == 1) {",
    "    js_template <- paste(",
    "      \"function(row, data) {\",",
    "      sprintf(\"  var supportHtml = data[%d];\", support_index - 1L),",
    "      sprintf(\"  var opposeHtml = data[%d];\", oppose_index - 1L),",
    "      sprintf(\"  var individualId = data[%d];\", participant_target),",
    "      \"  var modal = $('#individualModal');\",",
    "      \"  $(row).css('cursor', 'pointer');\",",
    "      \"  $(row).off('click').on('click', function() {\",",
    "      \"    if (modal.length === 0) { return; }\",",
    "      \"    if ((!supportHtml || supportHtml === '') && (!opposeHtml || opposeHtml === '')) { return; }\",",
    "      \"    var content = '<div style=\\\\\\\"max-height:70vh;overflow-y:auto;\\\\\\\">' +\",",
    "      \"      '<h3>Individual ' + individualId + '</h3>' +\",",
    "      \"      '<div style=\\\\\\\"display:flex;gap:24px;\\\\\\\">' +\",",
    "      \"      '<div style=\\\\\\\"flex:1;\\\\\\\"><h4>Variables that support the change</h4><ul>' +\",",
    "      \"      (supportHtml ? supportHtml : '<li>None</li>') + '</ul></div>' +\",",
    "      \"      '<div style=\\\\\\\"flex:1;\\\\\\\"><h4>Variables that do not support the change</h4><ul>' +\",",
    "      \"      (opposeHtml ? opposeHtml : '<li>None</li>') + '</ul></div>' +\",",
    "      \"      '</div></div>';\",",
    "      \"    $('#individualModalContent').html(content);\",",
    "      \"    modal.show();\",",
    "      \"  });\",",
    "      \"}\",",
    "      sep = \"\\n\"",
    "    )",
    "    row_callback <- DT::JS(js_template)",
    "  }",
    "  datatable(",
    "    display_data,",
    "    options = list(",
    "      scrollX = TRUE,",
    "      columnDefs = column_defs,",
    "      rowCallback = row_callback",
    "    ),",
    "    escape = FALSE,",
    "    selection = 'none',",
    "    rownames = FALSE",
    "  )",
    "}",
    "```",
    ""

  )

  writeLines(report_contents, report_path)

  list(
    report_path = normalizePath(report_path, winslash = "/", mustWork = FALSE),
    assets_dir = normalizePath(assets_dir, winslash = "/", mustWork = FALSE),
    importance_path = normalizePath(importance_path, winslash = "/", mustWork = FALSE),
    summary_path = normalizePath(summary_path, winslash = "/", mustWork = FALSE),
    rf_report_path = if (!is.null(rf_report_path)) normalizePath(rf_report_path, winslash = "/", mustWork = FALSE) else NULL,
    svm_report_path = if (!is.null(svm_report_path)) normalizePath(svm_report_path, winslash = "/", mustWork = FALSE) else NULL,
    anomaly_report_path = if (!is.null(anomaly_report_path)) normalizePath(anomaly_report_path, winslash = "/", mustWork = FALSE) else NULL,
    domain_expert_path = if (!is.null(domain_expert_path)) normalizePath(domain_expert_path, winslash = "/", mustWork = FALSE) else NULL,
    individual_interpretability_path = if (!is.null(individual_interpretability_path)) normalizePath(individual_interpretability_path, winslash = "/", mustWork = FALSE) else NULL
  )
}
